<a href="https://colab.research.google.com/github/Kerhoff/data_science_libraries/blob/lesson_1/lukashkin_lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тема “Вычисления с помощью Numpy”

## Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. 
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. 

Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],[2, 8], [3, 11], [3, 10], [1, 8]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  8]])

In [3]:
a.shape

(5, 2)

In [4]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.6])

## Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. 

Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [5]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.6],
       [ 0. , -0.6],
       [ 1. ,  2.4],
       [ 1. ,  1.4],
       [-1. , -0.6]])

In [6]:
a_centered.shape

(5, 2)

In [8]:
a.shape == a_centered.shape

True

## Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


### Вариант 1

In [9]:
a_centered

array([[-1. , -2.6],
       [ 0. , -0.6],
       [ 1. ,  2.4],
       [ 1. ,  1.4],
       [-1. , -0.6]])

In [10]:
a_centered_sp = a_centered[0][0] * a_centered[0][1] + a_centered[1][0] * a_centered[1][1] + a_centered[2][0] * a_centered[2][1] + a_centered[3][0] * a_centered[3][1] + a_centered[4][0] * a_centered[4][1]
a_centered_sp

7.0

In [11]:
a_centered_sp / (a.shape[0] - 1)

1.75

### Вариант 2

In [12]:
a_centered

array([[-1. , -2.6],
       [ 0. , -0.6],
       [ 1. ,  2.4],
       [ 1. ,  1.4],
       [-1. , -0.6]])

In [13]:
b = np.array([el[0] for el in a_centered])
b

array([-1.,  0.,  1.,  1., -1.])

In [14]:
c = np.array([el[1] for el in a_centered])
c

array([-2.6, -0.6,  2.4,  1.4, -0.6])

In [15]:
a_centered_sp = b @ c
a_centered_sp

7.0

In [16]:
a_centered_sp / (a_centered.shape[0] - 1)

1.75

## Задание 4

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.



В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [17]:
a = np.array([[1, 6],[2, 8], [3, 11], [3, 10], [1, 8]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  8]])

In [18]:
a_tr = np.transpose(a)
a_tr

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  8]])

In [19]:
a.T

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  8]])

In [20]:
np.cov(a,rowvar=False)

array([[1.  , 1.75],
       [1.75, 3.8 ]])

In [21]:
np.cov(a_tr)

array([[1.  , 1.75],
       [1.75, 3.8 ]])

# Тема “Работа с данными в Pandas”

## Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [22]:
import pandas as pd

In [23]:
authors_data = {'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']}
authors_data

{'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']}

In [24]:
authors = pd.DataFrame(authors_data)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [25]:
books_data = {
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]
}
books_data

{'author_id': [1, 1, 1, 2, 2, 3, 3],
 'book_title': ['Отцы и дети',
  'Рудин',
  'Дворянское гнездо',
  'Толстый и тонкий',
  'Дама с собачкой',
  'Гроза',
  'Таланты и поклонники'],
 'price': [450, 300, 350, 500, 450, 370, 290]}

In [26]:
books = pd.DataFrame(books_data)
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [27]:
authors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   author_id    3 non-null      int64 
 1   author_name  3 non-null      object
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes


In [28]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   author_id   7 non-null      int64 
 1   book_title  7 non-null      object
 2   price       7 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 296.0+ bytes


## Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [30]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [31]:
top5 = authors_price.sort_values(by="price", ascending=False).head(5)
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [32]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

### Вариант 1

In [ ]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [ ]:
df_groupby = authors_price.groupby('author_name')
df_groupby

In [ ]:
min_price = df_groupby['price'].min()
min_price

author_name
Островский    290
Тургенев      300
Чехов         450
Name: price, dtype: int64

In [ ]:
max_price = df_groupby['price'].max()
max_price

author_name
Островский    370
Тургенев      450
Чехов         500
Name: price, dtype: int64

In [ ]:
mean_price = df_groupby['price'].mean().round(2)
mean_price

author_name
Островский    330.00
Тургенев      366.67
Чехов         475.00
Name: price, dtype: float64

In [ ]:
authors_stat = pd.DataFrame({
    'min_price': min_price,
    'max_price': max_price,
    'mean_price': mean_price
})
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370      330.00
Тургенев           300        450      366.67
Чехов              450        500      475.00

In [ ]:
authors_stat = authors_price.groupby('author_name').agg({'price': [('min_price', 'min'), ('max_price', 'max'), ('mean_price', 'mean')]})
authors_stat

price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000

### Вариант 2

In [ ]:
from functools import reduce

In [ ]:
df_min_price = min_price.to_frame()
df_min_price = df_min_price.rename(columns={'price':'min_price'})
df_min_price

min_price
author_name           
Островский         290
Тургенев           300
Чехов              450

In [ ]:
df_max_price = max_price.to_frame()
df_max_price = df_max_price.rename(columns={'price':'max_price'})
df_max_price

max_price
author_name           
Островский         370
Тургенев           450
Чехов              500

In [ ]:
df_mean_price = mean_price.to_frame()
df_mean_price = df_mean_price.rename(columns={'price':'mean_price'})
df_mean_price

mean_price
author_name            
Островский       330.00
Тургенев         366.67
Чехов            475.00

In [ ]:
dfs = [df_min_price, df_max_price, df_mean_price]

In [ ]:
df_final = reduce(lambda left, right: pd.merge(left, right, on='author_name'), dfs)
df_final

min_price  max_price  mean_price
author_name                                  
Островский         290        370      330.00
Тургенев           300        450      366.67
Чехов              450        500      475.00

## Задание 5**

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.

Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [ ]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [ ]:
cover_data = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
cover_data

['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [ ]:
authors_price['cover'] = cover_data
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [ ]:
?pd.pivot_table

In [ ]:
pd.pivot_table(authors_price, values='price', fill_value=0, index=['author_name'], columns=['cover'], aggfunc=np.sum)

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
book_info = pd.pivot_table(authors_price, values='price', fill_value=0, index=['author_name'], columns=['cover'], aggfunc=np.sum)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [ ]:
?pd.to_pickle()

In [ ]:
pd.to_pickle(book_info, '/content/drive/MyDrive/Colab Notebooks/Библиотеки Python для DataScience/HW/book_info.pkl')

In [ ]:
book_info2 = pd.read_pickle('/content/drive/MyDrive/Colab Notebooks/Библиотеки Python для DataScience/HW/book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950